# Analiza slovenskih gora

V nadaljevanju bom analizirala zbrane podatke o slovenskih gorah iz spletne strani [hribi.net](https://www.hribi.net).
Za vsako goro imamo podatke o njenem imenu, kateremu gorovju pripada, višini, številu ogledov na spletni strani, priljubljenosti (v %) in podatke o poteh, ki vodijo do vrha. Za vsako pot poznamo njeno ime, predviden čas in zahtevnost.
Analiza bo sestavljena iz treh delov:
- Analiza gorovij
- Analiza poti
- Analiza gora

Najprej uvozimo podatke iz datotek `gore.csv` in `poti.csv`.

In [21]:
import pandas as pd
gore = pd.read_csv("gore.csv", index_col="id")
poti = pd.read_csv("poti.csv", index_col="gora_id")

Tako zdaj izgledajo naši podatki.

In [22]:
display(gore)
display(poti)

,ime,gorovje,visina,ogledi,priljubljenost,stevilo_poti
id,,,,,,
1,Veliki Snežnik,"Goriško, Notranjsko in Snežniško hribovje",1796,1052077,99,10
2,Mali Snežnik,"Goriško, Notranjsko in Snežniško hribovje",1694,439327,86,4
3,Mali Golak,"Goriško, Notranjsko in Snežniško hribovje",1495,710879,98,7
4,Srednji Golak,"Goriško, Notranjsko in Snežniško hribovje",1480,403846,83,2
5,Smrekov vrh,"Goriško, Notranjsko in Snežniško hribovje",1449,4490,40,1
...,...,...,...,...,...,...
2471,Ormoško jezero,"Strojna, Košenjak, Kozjak in Slovenske gorice",186,308,15,1
2472,Babičev mlin na Muri,"Strojna, Košenjak, Kozjak in Slovenske gorice",182,1843,31,2
2473,Gramoznica Krapje,"Strojna, Košenjak, Kozjak in Slovenske gorice",180,61,3,1
2474,Brod na Muri (Melinci),"Strojna, Košenjak, Kozjak in Slovenske gorice",175,196876,63,1
2475,Razkriški kot (sotočje Mure in Ščavnice),"Strojna, Košenjak, Kozjak in Slovenske gorice",169,585,22,2

,ime,cas,zahtevnost
gora_id,,,
1,Sviščaki - Veliki Snežnik,130,lahka označena pot
1,Kapetanova bajta - Veliki Snežnik,55,lahka označena pot
1,Leskova dolina - Veliki Snežnik,195,lahka označena pot
1,Snežniška Grda jama - Veliki Snežnik (čez Mali...,85,lahka označena pot
1,Gašperjev hrib - Veliki Snežnik,90,lahka označena pot
...,...,...,...
2472,Beltinci - Babičev mlin na Muri,95,lahka označena pot
2473,Zgornje Krapje - Gramoznica Krapje,20,lahka neoznačena steza
2474,Mota - Brod na Muri (Melinci) (od mrtvic do reke),45,lahka označena pot
2475,Razkrižje - Razkriški kot (sotočje Mure in Šča...,75,lahka označena pot
2475,Gibina - Razkriški kot (sotočje Mure in Ščavnice),6,lahka označena pot

## Analiza gorovij

Najprej gore razvrstimo glede na gorovje, v katerem ležijo.

> Opomba: Poimenovanja na spletni strani niso povsem geografsko natančna. Gre bolj za regije kot pa za klasična gorovja, vendar bom zaradi skladnosti z virom uporabljala izraz *gorovje*.

In [49]:
gore.groupby("gorovje").size().sort_values(ascending=False)

gorovje
Julijske Alpe                                    613
Karavanke                                        394
Goriško, Notranjsko in Snežniško hribovje        309
Posavsko hribovje in Dolenjska                   307
Kamniško Savinjske Alpe                          297
Škofjeloško, Cerkljansko hribovje in Jelovica    145
Pohorje, Dravinjske gorice in Haloze             128
Strojna, Košenjak, Kozjak in Slovenske gorice    115
Polhograjsko hribovje in Ljubljana                92
Prekmurje                                         75
dtype: int64

Poglejmo koliko je povprečna višina posameznega gorovja in katero je najbolj priljbljeno.

In [50]:
gore.groupby("gorovje")["visina"].mean().round().sort_values(ascending=False)

gorovje
Julijske Alpe                                    1645.0
Kamniško Savinjske Alpe                          1349.0
Karavanke                                        1273.0
Škofjeloško, Cerkljansko hribovje in Jelovica     956.0
Pohorje, Dravinjske gorice in Haloze              913.0
Goriško, Notranjsko in Snežniško hribovje         764.0
Posavsko hribovje in Dolenjska                    644.0
Polhograjsko hribovje in Ljubljana                622.0
Strojna, Košenjak, Kozjak in Slovenske gorice     531.0
Prekmurje                                         295.0
Name: visina, dtype: float64

In [55]:
gore.groupby("gorovje")["priljubljenost"].mean().round().sort_values(ascending=False)

gorovje
Kamniško Savinjske Alpe                          72.0
Julijske Alpe                                    70.0
Polhograjsko hribovje in Ljubljana               67.0
Goriško, Notranjsko in Snežniško hribovje        63.0
Škofjeloško, Cerkljansko hribovje in Jelovica    60.0
Karavanke                                        59.0
Posavsko hribovje in Dolenjska                   50.0
Pohorje, Dravinjske gorice in Haloze             41.0
Strojna, Košenjak, Kozjak in Slovenske gorice    31.0
Prekmurje                                        24.0
Name: priljubljenost, dtype: float64